---
output: html_document
editor_options: 
  chunk_output_type: console
---

#GFP sig genes (2769)
```{r}
#Raw counts file
counts_matrix <- read.table("/scratch/Shares/rinn/lincxpress/GFP_12Sept2024/rnaseq/nextflow_results/star_salmon/salmon.merged.gene_counts.tsv", header=TRUE, row.names=1)

g2s <- data.frame(
  gene_id = rownames(counts_matrix),
  gene_name = counts_matrix[, 1]
)

View(g2s)

# Remove gene name column for future use in DESEQ2
counts_matrix <-counts_matrix[, -1] 

# Round counts to integer mode required for DESEQ2
counts_integer <- round(counts_matrix)

View(counts_matrix)
View(counts_integer)

deseq_samples <- data.frame(
  sample_id = colnames(counts_matrix))

split_values <- strsplit(deseq_samples$sample_id, "_")

View(split_values)
# So here we will go through each row of split_values and run a "generic function(x)" 
# We will then retain the second item which is the time point value in sample_id
time_values <- sapply(split_values, function(x) x[[2]])

# Similar to above we are using apply to grab the third fragment in split_values (replicate value)
replicate_values <- sapply(split_values, function(x) x[[3]])

# Adding replicate and time point into samplesheet for DESEQ2
deseq_samples$time_point <- time_values

# Now let's add another column for replicate
deseq_samples$replicate <- replicate_values

View(deseq_samples)

#facotring timepoint column
deseq_samples$time_point <- factor(deseq_samples$time_point)
deseq_samples$replicate <- factor(deseq_samples$replicate)
```

```{r}
dds_time_point <- DESeqDataSetFromMatrix(countData = counts_integer,
                              colData = deseq_samples,
                              design = ~ time_point)


dds_time_point <- DESeq(dds_time_point,  test = "LRT", reduced = ~ 1)

```

```{r}

resultsNames(dds_time_point)

result_names <- resultsNames(dds_time_point)

results_names <- result_names[-1]
View(results_names)

GFP_res_df <- data.frame("gene_id" = character(), 
                     "baseMean" = numeric(), 
                     "log2FoldChange" = numeric(), 
                     "lfcSE" = numeric(),
                     "stat" = numeric(),
                     "pvalue" = numeric(),
                     "padj" = numeric(),
                     "gene_name" = character(),
                     "result_name" = character())

# For loop to get all results per time point  

for(i in 1:length(results_names)) {
  results_name <- results_names[i]
  res <- results(dds_time_point, name = results_name)
  tmp_res_df <- res %>% as.data.frame() %>%
    rownames_to_column("gene_id") %>%
    merge(g2s) %>%
    mutate(result_name = results_name)
  GFP_res_df <- dplyr::bind_rows(GFP_res_df, tmp_res_df)
  
}

# Calculate the maximum fold-change in any one timepoint
  GFP_maxfc <- GFP_res_df %>%
    group_by(gene_id) %>%
    summarize(max_fc = max(abs(log2FoldChange))) 
  
  # merge max shrnklfc into dataframe
  GFP_res_df <- GFP_res_df %>%
    left_join(GFP_maxfc)
  
  GFP_res_df <- GFP_res_df %>% 
  filter(padj <= 0.05)
  
  GFP_sig <- GFP_res_df %>%
  filter(max_fc >= 1)
  
  length(unique(GFP_sig$gene_id))

save(GFP_res_df, GFP_sig, file = "GFP_res_df.RData")
```

#FENDRR sig genes (904, after filter GFP_sig 440)
```{r}
#Raw counts file
counts_matrix <- read.table("/scratch/Shares/rinn/lincxpress/FENDRR/rnaseq/nextflow_results/star_salmon/salmon.merged.gene_counts.tsv", header=TRUE, row.names=1)

g2s <- data.frame(
  gene_id = rownames(counts_matrix),
  gene_name = counts_matrix[, 1]
)

View(g2s)

# Remove gene name column for future use in DESEQ2
counts_matrix <-counts_matrix[, -1] 

# Round counts to integer mode required for DESEQ2
counts_integer <- round(counts_matrix)

View(counts_matrix)
View(counts_integer)

deseq_samples <- data.frame(
  sample_id = colnames(counts_matrix))

split_values <- strsplit(deseq_samples$sample_id, "_")

View(split_values)
# So here we will go through each row of split_values and run a "generic function(x)" 
# We will then retain the second item which is the time point value in sample_id
time_values <- sapply(split_values, function(x) x[[2]])

# Similar to above we are using apply to grab the third fragment in split_values (replicate value)
replicate_values <- sapply(split_values, function(x) x[[3]])

# Adding replicate and time point into samplesheet for DESEQ2
deseq_samples$time_point <- time_values

# Now let's add another column for replicate
deseq_samples$replicate <- replicate_values

View(deseq_samples)

#facotring timepoint column
deseq_samples$time_point <- factor(deseq_samples$time_point)
deseq_samples$replicate <- factor(deseq_samples$replicate)
```

```{r}

dds_time_point <- DESeqDataSetFromMatrix(countData = counts_integer,
                              colData = deseq_samples,
                              design = ~ time_point)


dds_time_point <- DESeq(dds_time_point,  test = "LRT", reduced = ~ 1)

```

```{r}

resultsNames(dds_time_point)

result_names <- resultsNames(dds_time_point)

results_names <- result_names[-1]
View(results_names)

FENDRR_res_df <- data.frame("gene_id" = character(), 
                     "baseMean" = numeric(), 
                     "log2FoldChange" = numeric(), 
                     "lfcSE" = numeric(),
                     "stat" = numeric(),
                     "pvalue" = numeric(),
                     "padj" = numeric(),
                     "gene_name" = character(),
                     "result_name" = character())

# For loop to get all results per time point  

for(i in 1:length(results_names)) {
  results_name <- results_names[i]
  res <- results(dds_time_point, name = results_name)
  tmp_res_df <- res %>% as.data.frame() %>%
    rownames_to_column("gene_id") %>%
    merge(g2s) %>%
    mutate(result_name = results_name,
           timepoint = as.numeric(sub("time_point_([0-9]+)_vs_0", "\\1", results_name)))
  FENDRR_res_df <- dplyr::bind_rows(FENDRR_res_df, tmp_res_df)
  
}

# Calculate the maximum fold-change in any one timepoint
  FENDRR_maxfc <- FENDRR_res_df %>%
    group_by(gene_id) %>%
    summarize(max_fc = max(abs(log2FoldChange))) 
  
  # merge max shrnklfc into dataframe
  FENDRR_res_df <- FENDRR_res_df %>%
    left_join(FENDRR_maxfc)
  
  FENDRR_res_df <- FENDRR_res_df %>% 
  filter(padj <= 0.05)
  
  # Add logical columns for upregulated and downregulated
FENDRR_res_df <- FENDRR_res_df %>%
  mutate(
    up = log2FoldChange >= 0 & padj < 0.05,
    down = log2FoldChange <= 0 & padj < 0.05
  )

# Create a summary table to count up and down regulations per gene across comparisons
trend_summary <- FENDRR_res_df %>%
  group_by(gene_id) %>%
  summarize(
    up_count = sum(up, na.rm = TRUE),
    down_count = sum(down, na.rm = TRUE),
    total_comparisons = n()  # Total number of comparisons (rows)
  ) %>% filter(total_comparisons > 6) 

# Identify sig up-regulated and down-regulated genes
FENDRR_up<- trend_summary %>%
  filter(up_count == 7)

FENDRR_down<- trend_summary %>%
  filter(down_count == 7)
# Merge back to get the log2FoldChange for plotting
FENDRR_sig <- FENDRR_res_df %>%
  filter(gene_id %in% FENDRR_up$gene_id | gene_id %in% FENDRR_down$gene_id)

  FENDRR_sig <- FENDRR_sig %>%
  filter(max_fc >= 1)
  
    length(unique(FENDRR_sig$gene_id))
  
  load("/scratch/Shares/rinn/ML/RNAseq/GFP_res_df.RData")
FENDRR_sig <- FENDRR_sig %>%
  filter(!gene_id %in% GFP_sig$gene_id)
  
  length(unique(FENDRR_sig$gene_id))

save(FENDRR_res_df, FENDRR_sig, file = "FENDRR_res_df.RData")
```

#LRT model time*condition for FENDRR (445, after filter GFP 252)
```{r}
# Load both datasets
GFP_counts <- read.table("/scratch/Shares/rinn/lincxpress/GFP_12Sept2024/rnaseq/nextflow_results/star_salmon/salmon.merged.gene_counts.tsv", header=TRUE, row.names=1)
FENDRR_counts <- read.table("/scratch/Shares/rinn/lincxpress/FENDRR/rnaseq/nextflow_results/star_salmon/salmon.merged.gene_counts.tsv", header=TRUE, row.names=1)

#make g2s
g2s <- data.frame(
  gene_id = rownames(GFP_counts),
  gene_name = GFP_counts[, 1]
)
#Remove gene_name
FENDRR_counts <- FENDRR_counts[, -1]
GFP_counts <- GFP_counts[, -1]

# Round counts to integer mode required for DESEQ2
GFP_integer <- round(GFP_counts)
FENDRR_integer <- round(FENDRR_counts)

# Ensure both datasets have the same genes (row order)
all(rownames(GFP_integer) == rownames(FENDRR_integer))


# Combine the GFP and FENDRR counts into a single matrix
combined_counts <- cbind(GFP_integer, FENDRR_integer)


# Create condition, time, and replicate vectors
GFP_colnames <- colnames(GFP_integer)
FENDRR_colnames <- colnames(FENDRR_integer)
```

```{r}
#factor
condition <- factor(c(rep("GFP", length(GFP_colnames)), rep("FENDRR", length(FENDRR_colnames))))
time <- factor(c(sapply(strsplit(GFP_colnames, "_"), `[`, 2), sapply(strsplit(FENDRR_colnames, "_"), `[`, 2)))

condition <- relevel(condition, ref = "GFP")
time <- factor(time, levels = c("0", "2", "4", "8", "16", "24", "48", "96"))
time <- relevel(time, ref = "0")

col_data <- data.frame(sample_id = colnames(combined_counts), condition = condition, time = time)

levels(col_data$condition)
levels(col_data$time)


stopifnot(all(colnames(combined_counts) == col_data$sample_id))

# Create the DESeqDataSet
dds <- DESeqDataSetFromMatrix(countData = combined_counts, colData = col_data, design = ~ time*condition )
# Perform the LRT to find genes changing due to FENDRR
dds <- DESeq(dds, test = "LRT", reduced = ~ time + condition)

```

```{r}
#Curating all results into data frame
resultsNames(dds)

result_names <- resultsNames(dds)

results_names <- result_names[-1]
View(results_names)

FENDRR_res_df_2 <- data.frame("gene_id" = character(), 
                     "baseMean" = numeric(), 
                     "log2FoldChange" = numeric(), 
                     "lfcSE" = numeric(),
                     "stat" = numeric(),
                     "pvalue" = numeric(),
                     "padj" = numeric(),
                     "gene_name" = character(),
                     "result_name" = character())

# For loop to get all results per time point  

for(i in 1:length(results_names)) {
  results_name <- results_names[i]
  res <- results(dds, name = results_name)
  tmp_res_df <- res %>% as.data.frame() %>%
    rownames_to_column("gene_id") %>%
    merge(g2s) %>%
    mutate(result_name = results_name)
  FENDRR_res_df_2 <- dplyr::bind_rows(FENDRR_res_df_2, tmp_res_df)
  
}

dynamic_res <- result_names[grepl("conditionFENDRR", result_names)]
# cleaning up each result file
  FENDRR_res_df_2 <- lapply(dynamic_res, function(x) {
    results(dds, 
            name = x) %>%
      as.data.frame() %>%
      rownames_to_column("gene_id") %>% 
      merge(g2s) %>%
      mutate(result_name = x,
             timepoint = as.numeric(sub("time([0-9]+)\\.conditionFENDRR", "\\1", x)))
  }) %>% bind_rows()

# Calculate the maximum fold-change in any one timepoint
  FENDRR_maxfc <- FENDRR_res_df_2 %>%
    group_by(gene_id) %>%
    summarize(max_fc = max(abs(log2FoldChange))) 
  
  # merge max shrnklfc into dataframe
  FENDRR_res_df_2 <- FENDRR_res_df_2 %>%
    left_join(FENDRR_maxfc)
  
  FENDRR_res_df_2 <- FENDRR_res_df_2 %>% 
  filter(padj <= 0.05)
  
  # Add logical columns for upregulated and downregulated
FENDRR_res_df_2 <- FENDRR_res_df_2 %>%
  mutate(
    up = log2FoldChange >= 0 & padj < 0.05,
    down = log2FoldChange <= 0 & padj < 0.05
  )

# Create a summary table to count up and down regulations per gene across comparisons
trend_summary <- FENDRR_res_df_2 %>%
  group_by(gene_id) %>%
  summarize(
    up_count = sum(up, na.rm = TRUE),
    down_count = sum(down, na.rm = TRUE),
    total_comparisons = n()  # Total number of comparisons (rows)
  ) %>% filter(total_comparisons > 6) 

# Identify sig up-regulated and down-regulated genes
FENDRR_up<- trend_summary %>%
  filter(up_count == 7)

FENDRR_down<- trend_summary %>%
  filter(down_count == 7)
# Merge back to get the log2FoldChange for plotting
FENDRR_sig_2 <- FENDRR_res_df_2 %>%
  filter(gene_id %in% FENDRR_up$gene_id | gene_id %in% FENDRR_down$gene_id)

  FENDRR_sig_2 <- FENDRR_sig_2 %>%
  filter(max_fc >= 1)
  
    length(unique(FENDRR_sig_2$gene_id))
  
  load("/scratch/Shares/rinn/ML/RNAseq/GFP_res_df.RData")
FENDRR_sig_2 <- FENDRR_sig_2 %>%
  filter(!gene_id %in% GFP_sig$gene_id)
  
  length(unique(FENDRR_sig_2$gene_id))

save(FENDRR_sig_2, FENDRR_res_df_2, file = "FENDRR_res_df_2.RData")
```

#overlap sig gene for both model of FENDRR (79)
```{r}
# Find overlapping gene IDs
overlap_gene_ids <- intersect(FENDRR_sig$gene_id, FENDRR_sig_2$gene_id)

# Filter the original data frames to include only the overlapping genes
FENDRR_sig_overlap <- FENDRR_sig[FENDRR_sig$gene_id %in% overlap_gene_ids, ]
FENDRR_sig_2_overlap <- FENDRR_sig_2[FENDRR_sig_2$gene_id %in% overlap_gene_ids, ]

length(unique(FENDRR_sig_2_overlap$gene_id))

```

#FENDRR sig gene LFC plot
```{r}
#plot each gene LFC of time model
# Add a 0 time_point
  FENDRR_sig_zero <- FENDRR_sig %>%
    dplyr::select(gene_id, gene_name, baseMean) %>%
    distinct() %>%
    mutate(log2FoldChange = 0,
           timepoint = 0) 

FENDRR_sig <- FENDRR_sig %>%
    bind_rows(FENDRR_sig_zero)

ggplot(FENDRR_sig, aes(x = timepoint, y = log2FoldChange, group = gene_id)) +
    geom_hline(yintercept = 0) +
    geom_line(alpha = 0.2, color = "gray70") +
    geom_point(alpha = 0.4) +
    facet_wrap(~gene_name, scales = "free_y") +
    scale_x_continuous(breaks = c(0, 2, 4, 8, 16, 24, 48, 96), labels = c("0", "2", "4", "8", "16", "24", "48", "96") )

ggsave(path = "/scratch/Shares/rinn/ML/RNAseq/", filename = "FENDRR_sig_lfc_individule_from_time_model.pdf", height = 100, width = 125, limitsize = FALSE)

#plot each gene LFC of time model
# Add a 0 time_point
  FENDRR_sig_zero_2 <- FENDRR_sig_2 %>%
    dplyr::select(gene_id, gene_name, baseMean) %>%
    distinct() %>%
    mutate(log2FoldChange = 0,
           timepoint = 0) 

FENDRR_sig_2 <- FENDRR_sig_2 %>%
    bind_rows(FENDRR_sig_zero_2)

ggplot(FENDRR_sig_2, aes(x = timepoint, y = log2FoldChange, group = gene_id)) +
    geom_hline(yintercept = 0) +
    geom_line(alpha = 0.2, color = "gray70") +
    geom_point(alpha = 0.4) +
    facet_wrap(~gene_name, scales = "free_y") +
    scale_x_continuous(breaks = c(0, 2, 4, 8, 16, 24, 48, 96), labels = c("0", "2", "4", "8", "16", "24", "48", "96") )

ggsave(path = "/scratch/Shares/rinn/ML/RNAseq/", filename = "FENDRR_sig_lfc_individule_from_time_condition_model.pdf", height = 100, width = 125, limitsize = FALSE)

#plot each gene LFC of overlap sig gene in both model
# Add a 0 time_point
  FENDRR_sig_overlap_zero <- FENDRR_sig_2_overlap %>%
    dplyr::select(gene_id, gene_name, baseMean) %>%
    distinct() %>%
    mutate(log2FoldChange = 0,
           timepoint = 0) 

FENDRR_sig_2_overlap <- FENDRR_sig_2_overlap %>%
    bind_rows(FENDRR_sig_overlap_zero)

ggplot(FENDRR_sig_2_overlap, aes(x = timepoint, y = log2FoldChange, group = gene_id)) +
    geom_hline(yintercept = 0) +
    geom_line(alpha = 0.2, color = "gray70") +
    geom_point(alpha = 0.4) +
    facet_wrap(~gene_name, scales = "free_y") +
    scale_x_continuous(breaks = c(0, 2, 4, 8, 16, 24, 48, 96), labels = c("0", "2", "4", "8", "16", "24", "48", "96") )

ggsave(path = "/scratch/Shares/rinn/ML/RNAseq/", filename = "FENDRR_sig_lfc_individule_overlap.pdf", height = 30, width = 45, limitsize = FALSE)
```

#FENDRR sig gene TPM plot
```{r}
#for time model
# Load TPM data for FENDRR
tpm_FENDRR <- read.table("/scratch/Shares/rinn/lincxpress/FENDRR/rnaseq/nextflow_results/star_salmon/salmon.merged.gene_tpm.tsv", header=TRUE, row.names=1)

# Load TPM data for GFP
tpm_GFP <- read.table("/scratch/Shares/rinn/lincxpress/GFP_12Sept2024/rnaseq/nextflow_results/star_salmon/salmon.merged.gene_tpm.tsv", header=TRUE, row.names=1)

# Filter the TPM data for genes in sig_FENDRR_LRT_shrnklfc
filtered_tpm_FENDRR <- tpm_FENDRR[tpm_FENDRR$gene_name %in% FENDRR_sig$gene_name, ]
filtered_tpm_GFP <- tpm_GFP[tpm_GFP$gene_name %in% FENDRR_sig$gene_name, ]

# Reshape FENDRR TPM data to long format
tpm_long_FENDRR <- filtered_tpm_FENDRR %>%
  pivot_longer(
    cols = starts_with("FENDRR"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^FENDRR_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "FENDRR"  # Add a column to label as FENDRR
  )

# Reshape GFP TPM data to long format
tpm_long_GFP <- filtered_tpm_GFP %>%
  pivot_longer(
    cols = starts_with("GFP"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^GFP_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "GFP"  # Add a column to label as GFP
  )

# Combine FENDRR and GFP data into one data frame
tpm_combined_long <- bind_rows(tpm_long_FENDRR, tpm_long_GFP)

# Calculate mean TPM for each gene, time point, and condition
tpm_mean_combined <- tpm_combined_long %>%
  group_by(gene_name, time_point, condition) %>%
  summarise(mean_tpm = mean(tpm), .groups = 'drop')

# Plot the combined TPM values for FENDRR and GFP
ggplot(tpm_mean_combined, aes(x = time_point, y = mean_tpm, group = interaction(gene_name, condition))) +
  geom_line(aes(color = condition), alpha = 0.7) +  # Line colored by condition
  geom_point(alpha = 0.5) +  # Points for each mean TPM value
  facet_wrap(~ gene_name, scales = "free_y") +  # Separate plots for each gene
  labs(
    x = "Time Point (h)", 
    y = "Mean TPM", 
    color = "Condition"
  ) +
  theme_minimal() +  # Minimal theme
  scale_x_continuous(breaks = unique(tpm_mean_combined$time_point))  # Set x-axis breaks

# Save the plot
ggsave(
  path = "/scratch/Shares/rinn/ML/RNAseq/",
  filename = "FENDRR_GFP_sig_TPM_individule.pdf",
  height = 80, width = 125, limitsize = FALSE
)


#for time*condition model
# Filter the TPM data for genes in sig_FENDRR_LRT_shrnklfc
filtered_tpm_FENDRR <- tpm_FENDRR[tpm_FENDRR$gene_name %in% FENDRR_sig_2$gene_name, ]
filtered_tpm_GFP <- tpm_GFP[tpm_GFP$gene_name %in% FENDRR_sig_2$gene_name, ]

# Reshape FENDRR TPM data to long format
tpm_long_FENDRR <- filtered_tpm_FENDRR %>%
  pivot_longer(
    cols = starts_with("FENDRR"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^FENDRR_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "FENDRR"  # Add a column to label as FENDRR
  )

# Reshape GFP TPM data to long format
tpm_long_GFP <- filtered_tpm_GFP %>%
  pivot_longer(
    cols = starts_with("GFP"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^GFP_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "GFP"  # Add a column to label as GFP
  )

# Combine FENDRR and GFP data into one data frame
tpm_combined_long <- bind_rows(tpm_long_FENDRR, tpm_long_GFP)

# Calculate mean TPM for each gene, time point, and condition
tpm_mean_combined <- tpm_combined_long %>%
  group_by(gene_name, time_point, condition) %>%
  summarise(mean_tpm = mean(tpm), .groups = 'drop')

# Plot the combined TPM values for FENDRR and GFP
ggplot(tpm_mean_combined, aes(x = time_point, y = mean_tpm, group = interaction(gene_name, condition))) +
  geom_line(aes(color = condition), alpha = 0.7) +  # Line colored by condition
  geom_point(alpha = 0.5) +  # Points for each mean TPM value
  facet_wrap(~ gene_name, scales = "free_y") +  # Separate plots for each gene
  labs(
    x = "Time Point (h)", 
    y = "Mean TPM", 
    color = "Condition"
  ) +
  theme_minimal() +  # Minimal theme
  scale_x_continuous(breaks = unique(tpm_mean_combined$time_point))  # Set x-axis breaks

# Save the plot
ggsave(
  path = "/scratch/Shares/rinn/ML/RNAseq/",
  filename = "FENDRR_GFP_sig_2_TPM_individule.pdf",
  height = 55, width = 85, limitsize = FALSE
)

#for overlap sig genea
# Filter the TPM data for genes in sig_FENDRR_LRT_shrnklfc
filtered_tpm_FENDRR <- tpm_FENDRR[tpm_FENDRR$gene_name %in% FENDRR_sig_2_overlap$gene_name, ]
filtered_tpm_GFP <- tpm_GFP[tpm_GFP$gene_name %in% FENDRR_sig_2_overlap$gene_name, ]

# Reshape FENDRR TPM data to long format
tpm_long_FENDRR <- filtered_tpm_FENDRR %>%
  pivot_longer(
    cols = starts_with("FENDRR"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^FENDRR_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "FENDRR"  # Add a column to label as FENDRR
  )

# Reshape GFP TPM data to long format
tpm_long_GFP <- filtered_tpm_GFP %>%
  pivot_longer(
    cols = starts_with("GFP"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^GFP_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "GFP"  # Add a column to label as GFP
  )

# Combine FENDRR and GFP data into one data frame
tpm_combined_long <- bind_rows(tpm_long_FENDRR, tpm_long_GFP)

# Calculate mean TPM for each gene, time point, and condition
tpm_mean_combined <- tpm_combined_long %>%
  group_by(gene_name, time_point, condition) %>%
  summarise(mean_tpm = mean(tpm), .groups = 'drop')

# Plot the combined TPM values for FENDRR and GFP
ggplot(tpm_mean_combined, aes(x = time_point, y = mean_tpm, group = interaction(gene_name, condition))) +
  geom_line(aes(color = condition), alpha = 0.7) +  # Line colored by condition
  geom_point(alpha = 0.5) +  # Points for each mean TPM value
  facet_wrap(~ gene_name, scales = "free_y") +  # Separate plots for each gene
  labs(
    x = "Time Point (h)", 
    y = "Mean TPM", 
    color = "Condition"
  ) +
  theme_minimal() +  # Minimal theme
  scale_x_continuous(breaks = unique(tpm_mean_combined$time_point))  # Set x-axis breaks

# Save the plot
ggsave(
  path = "/scratch/Shares/rinn/ML/RNAseq/",
  filename = "FENDRR_GFP_sig_2_overlap_TPM_individule.pdf",
  height = 35, width = 55, limitsize = FALSE
)
```

#LINC00667 sig genes (1368, after filter GFP_sig 876)
```{r}
#Raw counts file
counts_matrix <- read.table("/scratch/Shares/rinn/lincxpress/LINC00667/rnaseq/nextflow_results/star_salmon/salmon.merged.gene_counts.tsv", header=TRUE, row.names=1)

g2s <- data.frame(
  gene_id = rownames(counts_matrix),
  gene_name = counts_matrix[, 1]
)

View(g2s)

# Remove gene name column for future use in DESEQ2
counts_matrix <-counts_matrix[, -1] 

# Round counts to integer mode required for DESEQ2
counts_integer <- round(counts_matrix)

View(counts_matrix)
View(counts_integer)

deseq_samples <- data.frame(
  sample_id = colnames(counts_matrix))

split_values <- strsplit(deseq_samples$sample_id, "_")

View(split_values)
# So here we will go through each row of split_values and run a "generic function(x)" 
# We will then retain the second item which is the time point value in sample_id
time_values <- sapply(split_values, function(x) x[[2]])

# Similar to above we are using apply to grab the third fragment in split_values (replicate value)
replicate_values <- sapply(split_values, function(x) x[[3]])

# Adding replicate and time point into samplesheet for DESEQ2
deseq_samples$time_point <- time_values

# Now let's add another column for replicate
deseq_samples$replicate <- replicate_values

View(deseq_samples)

#facotring timepoint column
deseq_samples$time_point <- factor(deseq_samples$time_point)
deseq_samples$replicate <- factor(deseq_samples$replicate)
```

```{r}

dds_time_point <- DESeqDataSetFromMatrix(countData = counts_integer,
                              colData = deseq_samples,
                              design = ~ time_point)


dds_time_point <- DESeq(dds_time_point,  test = "LRT", reduced = ~ 1)

```

```{r}

resultsNames(dds_time_point)

result_names <- resultsNames(dds_time_point)

results_names <- result_names[-1]
View(results_names)

LINC00667_res_df <- data.frame("gene_id" = character(), 
                     "baseMean" = numeric(), 
                     "log2FoldChange" = numeric(), 
                     "lfcSE" = numeric(),
                     "stat" = numeric(),
                     "pvalue" = numeric(),
                     "padj" = numeric(),
                     "gene_name" = character(),
                     "result_name" = character())

# For loop to get all results per time point  

for(i in 1:length(results_names)) {
  results_name <- results_names[i]
  res <- results(dds_time_point, name = results_name)
  tmp_res_df <- res %>% as.data.frame() %>%
    rownames_to_column("gene_id") %>%
    merge(g2s) %>%
    mutate(result_name = results_name,
           timepoint = as.numeric(sub("time_point_([0-9]+)_vs_0", "\\1", results_name)))
  LINC00667_res_df <- dplyr::bind_rows(LINC00667_res_df, tmp_res_df)
  
}

# Calculate the maximum fold-change in any one timepoint
  LINC00667_maxfc <- LINC00667_res_df %>%
    group_by(gene_id) %>%
    summarize(max_fc = max(abs(log2FoldChange))) 
  
  # merge max shrnklfc into dataframe
  LINC00667_res_df <- LINC00667_res_df %>%
    left_join(LINC00667_maxfc)
  
  LINC00667_res_df <- LINC00667_res_df %>% 
  filter(padj <= 0.05)
  
  # Add logical columns for upregulated and downregulated
LINC00667_res_df <- LINC00667_res_df %>%
  mutate(
    up = log2FoldChange >= 0 & padj < 0.05,
    down = log2FoldChange <= 0 & padj < 0.05
  )

# Create a summary table to count up and down regulations per gene across comparisons
trend_summary <- LINC00667_res_df %>%
  group_by(gene_id) %>%
  summarize(
    up_count = sum(up, na.rm = TRUE),
    down_count = sum(down, na.rm = TRUE),
    total_comparisons = n()  # Total number of comparisons (rows)
  ) %>% filter(total_comparisons > 6) 

# Identify sig up-regulated and down-regulated genes
LINC00667_up<- trend_summary %>%
  filter(up_count == 7)

LINC00667_down<- trend_summary %>%
  filter(down_count == 7)
# Merge back to get the log2FoldChange for plotting
LINC00667_sig <- LINC00667_res_df %>%
  filter(gene_id %in% LINC00667_up$gene_id | gene_id %in% LINC00667_down$gene_id)

  LINC00667_sig <- LINC00667_sig %>%
  filter(max_fc >= 1)
  
    length(unique(LINC00667_sig$gene_id))
  
  load("/scratch/Shares/rinn/ML/RNAseq/GFP_res_df.RData")
LINC00667_sig <- LINC00667_sig %>%
  filter(!gene_id %in% GFP_sig$gene_id)
  
  length(unique(LINC00667_sig$gene_id))

save(LINC00667_res_df, LINC00667_sig, file = "LINC00667_res_df.RData")
```

#LRT model time*condition for LINC00667 (1035, after filter GFP 605)
```{r}
# Load both datasets
GFP_counts <- read.table("/scratch/Shares/rinn/lincxpress/GFP_12Sept2024/rnaseq/nextflow_results/star_salmon/salmon.merged.gene_counts.tsv", header=TRUE, row.names=1)
LINC00667_counts <- read.table("/scratch/Shares/rinn/lincxpress/LINC00667/rnaseq/nextflow_results/star_salmon/salmon.merged.gene_counts.tsv", header=TRUE, row.names=1)

#make g2s
g2s <- data.frame(
  gene_id = rownames(GFP_counts),
  gene_name = GFP_counts[, 1]
)
#Remove gene_name
LINC00667_counts <- LINC00667_counts[, -1]
GFP_counts <- GFP_counts[, -1]

# Round counts to integer mode required for DESEQ2
GFP_integer <- round(GFP_counts)
LINC00667_integer <- round(LINC00667_counts)

# Ensure both datasets have the same genes (row order)
all(rownames(GFP_integer) == rownames(LINC00667_integer))


# Combine the GFP and LINC00667 counts into a single matrix
combined_counts <- cbind(GFP_integer, LINC00667_integer)


# Create condition, time, and replicate vectors
GFP_colnames <- colnames(GFP_integer)
LINC00667_colnames <- colnames(LINC00667_integer)
```

```{r}
#factor
condition <- factor(c(rep("GFP", length(GFP_colnames)), rep("LINC00667", length(LINC00667_colnames))))
time <- factor(c(sapply(strsplit(GFP_colnames, "_"), `[`, 2), sapply(strsplit(LINC00667_colnames, "_"), `[`, 2)))

condition <- relevel(condition, ref = "GFP")
time <- factor(time, levels = c("0", "2", "4", "8", "16", "24", "48", "96"))
time <- relevel(time, ref = "0")

col_data <- data.frame(sample_id = colnames(combined_counts), condition = condition, time = time)

levels(col_data$condition)
levels(col_data$time)


stopifnot(all(colnames(combined_counts) == col_data$sample_id))

# Create the DESeqDataSet
dds <- DESeqDataSetFromMatrix(countData = combined_counts, colData = col_data, design = ~ time*condition )
# Perform the LRT to find genes changing due to LINC00667
dds <- DESeq(dds, test = "LRT", reduced = ~ time + condition)

```

```{r}
#Curating all results into data frame
resultsNames(dds)

result_names <- resultsNames(dds)

results_names <- result_names[-1]
View(results_names)

LINC00667_res_df_2 <- data.frame("gene_id" = character(), 
                     "baseMean" = numeric(), 
                     "log2FoldChange" = numeric(), 
                     "lfcSE" = numeric(),
                     "stat" = numeric(),
                     "pvalue" = numeric(),
                     "padj" = numeric(),
                     "gene_name" = character(),
                     "result_name" = character())

# For loop to get all results per time point  

for(i in 1:length(results_names)) {
  results_name <- results_names[i]
  res <- results(dds, name = results_name)
  tmp_res_df <- res %>% as.data.frame() %>%
    rownames_to_column("gene_id") %>%
    merge(g2s) %>%
    mutate(result_name = results_name)
  LINC00667_res_df_2 <- dplyr::bind_rows(LINC00667_res_df_2, tmp_res_df)
  
}


dynamic_res <- result_names[grepl("conditionLINC00667", result_names)]
# cleaning up each result file
  LINC00667_res_df_2 <- lapply(dynamic_res, function(x) {
    results(dds, 
            name = x) %>%
      as.data.frame() %>%
      rownames_to_column("gene_id") %>% 
      merge(g2s) %>%
      mutate(result_name = x,
             timepoint = as.numeric(sub("time([0-9]+)\\.conditionLINC00667", "\\1", x)))
  }) %>% bind_rows()
  
LINC00667_res_df_2 <- LINC00667_res_df_2 %>%
  filter(padj <= 0.05)
LINC00667_res_df_2 <- LINC00667_res_df_2 %>%
  filter(abs(log2FoldChange) >= 1)
length(unique(LINC00667_res_df_2$gene_name))

# Calculate the maximum fold-change in any one timepoint
  LINC00667_maxfc <- LINC00667_res_df_2 %>%
    group_by(gene_id) %>%
    summarize(max_fc = max(abs(log2FoldChange))) 
  
  # merge max shrnklfc into dataframe
  LINC00667_res_df_2 <- LINC00667_res_df_2 %>%
    left_join(LINC00667_maxfc)
  
  LINC00667_res_df_2 <- LINC00667_res_df_2 %>% 
  filter(padj <= 0.05)
  
  # Add logical columns for upregulated and downregulated
LINC00667_res_df_2 <- LINC00667_res_df_2 %>%
  mutate(
    up = log2FoldChange >= 0 & padj < 0.05,
    down = log2FoldChange <= 0 & padj < 0.05
  )

# Create a summary table to count up and down regulations per gene across comparisons
trend_summary <- LINC00667_res_df_2 %>%
  group_by(gene_id) %>%
  summarize(
    up_count = sum(up, na.rm = TRUE),
    down_count = sum(down, na.rm = TRUE),
    total_comparisons = n()  # Total number of comparisons (rows)
  ) %>% filter(total_comparisons > 6) 

# Identify sig up-regulated and down-regulated genes
LINC00667_up<- trend_summary %>%
  filter(up_count == 7)

LINC00667_down<- trend_summary %>%
  filter(down_count == 7)
# Merge back to get the log2FoldChange for plotting
LINC00667_sig_2 <- LINC00667_res_df_2 %>%
  filter(gene_id %in% LINC00667_up$gene_id | gene_id %in% LINC00667_down$gene_id)

  LINC00667_sig_2 <- LINC00667_sig_2 %>%
  filter(max_fc >= 1)
   LINC00667_res_df_2 <- LINC00667_res_df_2 %>%
  filter(max_fc >= 1)
  
    length(unique(LINC00667_sig_2$gene_id))
  
  load("/scratch/Shares/rinn/ML/RNAseq/GFP_res_df.RData")
LINC00667_sig_2 <- LINC00667_sig_2 %>%
  filter(!gene_id %in% GFP_sig$gene_id)
  
  length(unique(LINC00667_sig_2$gene_id))

save(LINC00667_sig_2, LINC00667_res_df_2, file = "LINC00667_res_df_2.RData")
```

#overlap sig gene for both model of LINC00667 (291)
```{r}
# Find overlapping gene IDs
overlap_gene_ids <- intersect(LINC00667_sig$gene_id, LINC00667_sig_2$gene_id)

# Filter the original data frames to include only the overlapping genes
LINC00667_sig_overlap <- LINC00667_sig[LINC00667_sig$gene_id %in% overlap_gene_ids, ]
LINC00667_sig_2_overlap <- LINC00667_sig_2[LINC00667_sig_2$gene_id %in% overlap_gene_ids, ]

length(unique(LINC00667_sig_2_overlap$gene_id))

```

#LINC00667 sig gene LFC plot
```{r}
#plot each gene LFC of time model
# Add a 0 time_point
  LINC00667_sig_zero <- LINC00667_sig %>%
    dplyr::select(gene_id, gene_name, baseMean) %>%
    distinct() %>%
    mutate(log2FoldChange = 0,
           timepoint = 0) 

LINC00667_sig <- LINC00667_sig %>%
    bind_rows(LINC00667_sig_zero)

ggplot(LINC00667_sig, aes(x = timepoint, y = log2FoldChange, group = gene_id)) +
    geom_hline(yintercept = 0) +
    geom_line(alpha = 0.2, color = "gray70") +
    geom_point(alpha = 0.4) +
    facet_wrap(~gene_name, scales = "free_y") +
    scale_x_continuous(breaks = c(0, 2, 4, 8, 16, 24, 48, 96), labels = c("0", "2", "4", "8", "16", "24", "48", "96") )

ggsave(path = "/scratch/Shares/rinn/ML/RNAseq/", filename = "LINC00667_sig_lfc_individule_from_time_model.pdf", height = 100, width = 125, limitsize = FALSE)

#plot each gene LFC of time model
# Add a 0 time_point
  LINC00667_sig_zero_2 <- LINC00667_sig_2 %>%
    dplyr::select(gene_id, gene_name, baseMean) %>%
    distinct() %>%
    mutate(log2FoldChange = 0,
           timepoint = 0) 

LINC00667_sig_2 <- LINC00667_sig_2 %>%
    bind_rows(LINC00667_sig_zero_2)

ggplot(LINC00667_sig_2, aes(x = timepoint, y = log2FoldChange, group = gene_id)) +
    geom_hline(yintercept = 0) +
    geom_line(alpha = 0.2, color = "gray70") +
    geom_point(alpha = 0.4) +
    facet_wrap(~gene_name, scales = "free_y") +
    scale_x_continuous(breaks = c(0, 2, 4, 8, 16, 24, 48, 96), labels = c("0", "2", "4", "8", "16", "24", "48", "96") )

ggsave(path = "/scratch/Shares/rinn/ML/RNAseq/", filename = "LINC00667_sig_lfc_individule_from_time_condition_model.pdf", height = 100, width = 125, limitsize = FALSE)

#plot each gene LFC of overlap sig gene in both model
# Add a 0 time_point
  LINC00667_sig_overlap_zero <- LINC00667_sig_2_overlap %>%
    dplyr::select(gene_id, gene_name, baseMean) %>%
    distinct() %>%
    mutate(log2FoldChange = 0,
           timepoint = 0) 

LINC00667_sig_2_overlap <- LINC00667_sig_2_overlap %>%
    bind_rows(LINC00667_sig_overlap_zero)

ggplot(LINC00667_sig_2_overlap, aes(x = timepoint, y = log2FoldChange, group = gene_id)) +
    geom_hline(yintercept = 0) +
    geom_line(alpha = 0.2, color = "gray70") +
    geom_point(alpha = 0.4) +
    facet_wrap(~gene_name, scales = "free_y") +
    scale_x_continuous(breaks = c(0, 2, 4, 8, 16, 24, 48, 96), labels = c("0", "2", "4", "8", "16", "24", "48", "96") )

ggsave(path = "/scratch/Shares/rinn/ML/RNAseq/", filename = "LINC00667_sig_lfc_individule_overlap.pdf", height = 30, width = 45, limitsize = FALSE)
```

#LINC00667 sig gene TPM plot
```{r}
#for time model
# Load TPM data for LINC00667
tpm_LINC00667 <- read.table("/scratch/Shares/rinn/lincxpress/LINC00667/rnaseq/nextflow_results/star_salmon/salmon.merged.gene_tpm.tsv", header=TRUE, row.names=1)

# Load TPM data for GFP
tpm_GFP <- read.table("/scratch/Shares/rinn/lincxpress/GFP_12Sept2024/rnaseq/nextflow_results/star_salmon/salmon.merged.gene_tpm.tsv", header=TRUE, row.names=1)

# Filter the TPM data for genes in sig_LINC00667_LRT_shrnklfc
filtered_tpm_LINC00667 <- tpm_LINC00667[tpm_LINC00667$gene_name %in% LINC00667_sig$gene_name, ]
filtered_tpm_GFP <- tpm_GFP[tpm_GFP$gene_name %in% LINC00667_sig$gene_name, ]

# Reshape LINC00667 TPM data to long format
tpm_long_LINC00667 <- filtered_tpm_LINC00667 %>%
  pivot_longer(
    cols = starts_with("LINC00667"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^LINC00667_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "LINC00667"  # Add a column to label as LINC00667
  )

# Reshape GFP TPM data to long format
tpm_long_GFP <- filtered_tpm_GFP %>%
  pivot_longer(
    cols = starts_with("GFP"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^GFP_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "GFP"  # Add a column to label as GFP
  )

# Combine LINC00667 and GFP data into one data frame
tpm_combined_long <- bind_rows(tpm_long_LINC00667, tpm_long_GFP)

# Calculate mean TPM for each gene, time point, and condition
tpm_mean_combined <- tpm_combined_long %>%
  group_by(gene_name, time_point, condition) %>%
  summarise(mean_tpm = mean(tpm), .groups = 'drop')

# Plot the combined TPM values for LINC00667 and GFP
ggplot(tpm_mean_combined, aes(x = time_point, y = mean_tpm, group = interaction(gene_name, condition))) +
  geom_line(aes(color = condition), alpha = 0.7) +  # Line colored by condition
  geom_point(alpha = 0.5) +  # Points for each mean TPM value
  facet_wrap(~ gene_name, scales = "free_y") +  # Separate plots for each gene
  labs(
    x = "Time Point (h)", 
    y = "Mean TPM", 
    color = "Condition"
  ) +
  theme_minimal() +  # Minimal theme
  scale_x_continuous(breaks = unique(tpm_mean_combined$time_point))  # Set x-axis breaks

# Save the plot
ggsave(
  path = "/scratch/Shares/rinn/ML/RNAseq/",
  filename = "LINC00667_GFP_sig_TPM_individule.pdf",
  height = 80, width = 125, limitsize = FALSE
)


#for time*condition model
# Filter the TPM data for genes in sig_LINC00667_LRT_shrnklfc
filtered_tpm_LINC00667 <- tpm_LINC00667[tpm_LINC00667$gene_name %in% LINC00667_sig_2$gene_name, ]
filtered_tpm_GFP <- tpm_GFP[tpm_GFP$gene_name %in% LINC00667_sig_2$gene_name, ]

# Reshape LINC00667 TPM data to long format
tpm_long_LINC00667 <- filtered_tpm_LINC00667 %>%
  pivot_longer(
    cols = starts_with("LINC00667"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^LINC00667_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "LINC00667"  # Add a column to label as LINC00667
  )

# Reshape GFP TPM data to long format
tpm_long_GFP <- filtered_tpm_GFP %>%
  pivot_longer(
    cols = starts_with("GFP"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^GFP_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "GFP"  # Add a column to label as GFP
  )

# Combine LINC00667 and GFP data into one data frame
tpm_combined_long <- bind_rows(tpm_long_LINC00667, tpm_long_GFP)

# Calculate mean TPM for each gene, time point, and condition
tpm_mean_combined <- tpm_combined_long %>%
  group_by(gene_name, time_point, condition) %>%
  summarise(mean_tpm = mean(tpm), .groups = 'drop')

# Plot the combined TPM values for LINC00667 and GFP
ggplot(tpm_mean_combined, aes(x = time_point, y = mean_tpm, group = interaction(gene_name, condition))) +
  geom_line(aes(color = condition), alpha = 0.7) +  # Line colored by condition
  geom_point(alpha = 0.5) +  # Points for each mean TPM value
  facet_wrap(~ gene_name, scales = "free_y") +  # Separate plots for each gene
  labs(
    x = "Time Point (h)", 
    y = "Mean TPM", 
    color = "Condition"
  ) +
  theme_minimal() +  # Minimal theme
  scale_x_continuous(breaks = unique(tpm_mean_combined$time_point))  # Set x-axis breaks

# Save the plot
ggsave(
  path = "/scratch/Shares/rinn/ML/RNAseq/",
  filename = "LINC00667_GFP_sig_2_TPM_individule.pdf",
  height = 55, width = 85, limitsize = FALSE
)

#for overlap sig genea
# Filter the TPM data for genes in sig_LINC00667_LRT_shrnklfc
filtered_tpm_LINC00667 <- tpm_LINC00667[tpm_LINC00667$gene_name %in% LINC00667_sig_2_overlap$gene_name, ]
filtered_tpm_GFP <- tpm_GFP[tpm_GFP$gene_name %in% LINC00667_sig_2_overlap$gene_name, ]

# Reshape LINC00667 TPM data to long format
tpm_long_LINC00667 <- filtered_tpm_LINC00667 %>%
  pivot_longer(
    cols = starts_with("LINC00667"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^LINC00667_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "LINC00667"  # Add a column to label as LINC00667
  )

# Reshape GFP TPM data to long format
tpm_long_GFP <- filtered_tpm_GFP %>%
  pivot_longer(
    cols = starts_with("GFP"),
    names_to = c("time_point", "replicate"),
    names_pattern = "^GFP_(\\d+)_(\\d+)$",
    values_to = "tpm"
  ) %>%
  mutate(
    time_point = as.numeric(time_point),
    replicate = as.numeric(replicate),
    condition = "GFP"  # Add a column to label as GFP
  )

# Combine LINC00667 and GFP data into one data frame
tpm_combined_long <- bind_rows(tpm_long_LINC00667, tpm_long_GFP)

# Calculate mean TPM for each gene, time point, and condition
tpm_mean_combined <- tpm_combined_long %>%
  group_by(gene_name, time_point, condition) %>%
  summarise(mean_tpm = mean(tpm), .groups = 'drop')

# Plot the combined TPM values for LINC00667 and GFP
ggplot(tpm_mean_combined, aes(x = time_point, y = mean_tpm, group = interaction(gene_name, condition))) +
  geom_line(aes(color = condition), alpha = 0.7) +  # Line colored by condition
  geom_point(alpha = 0.5) +  # Points for each mean TPM value
  facet_wrap(~ gene_name, scales = "free_y") +  # Separate plots for each gene
  labs(
    x = "Time Point (h)", 
    y = "Mean TPM", 
    color = "Condition"
  ) +
  theme_minimal() +  # Minimal theme
  scale_x_continuous(breaks = unique(tpm_mean_combined$time_point))  # Set x-axis breaks

# Save the plot
ggsave(
  path = "/scratch/Shares/rinn/ML/RNAseq/",
  filename = "LINC00667_GFP_sig_2_overlap_TPM_individule.pdf",
  height = 55, width = 85, limitsize = FALSE
)
```