---
title: "Untitled"
output: html_document
date: "2024-02-29"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(dplyr)
library(ggplot2)
library(tidyr)
library(farver)
```


```{r}
data <- read.csv("/scratch/Shares/rinn/ML/qPCR/hiPSC_GFP_DOX time course&amp;pluripotency markers_admin_2024-01-09 13-38-34_CFX384 -  Gene Expression Results - Summary_0.csv")

data1 <- data %>%
  group_by(Time, Sample, Target) %>%
  mutate(mean_res = mean(Relative.Normalized.Expression), sd = sd(Relative.Normalized.Expression, na.rm=TRUE))
```

```{r}
nanog <- data1 %>%
  filter(Sample == "C5", Target == "NANOG") %>%
  select(Sample, Time, mean_res, sd) %>%
  distinct()

ggplot(nanog, aes(x=Time, y=mean_res)) +
  geom_bar(stat="identity") +
  geom_errorbar(aes(ymin=mean_res-sd, ymax=mean_res+sd)) +
  #scale_fill_manual(values=c('#923346','#0E1949', '#d65324')) + 
  ggtitle("NANOG expression by RT-qPCR") +
  xlab("Time after DOX induction") + 
  ylab("Relative expression to 0h") +
  theme_light() +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=15),
        plot.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15))

ggsave("NANOG.pdf", height = 5, width = 5)
```


```{r - stats // pluri}

# choose target
SOX2 <- data1 %>%
  filter(Target == "SOX2")

SOX2$Time <- ordered(SOX2$Time,
                         levels = c("0h", "12h", "24h", "48h", "96h"))
#run stats: Two way ANOVA (compare day of dif and condition to influence expression)
res.aov2 <- aov(Relative.Normalized.Expression ~ neuro_day * condition, data = SOX2) #synergistic effect using the *

summary(res.aov2)
#                    Df Sum Sq Mean Sq F value   Pr(>F)    
#neuro_day            3 1.5913  0.5304  725.16 4.43e-10 ***
#condition            2 0.1383  0.0692   94.57 2.71e-06 ***
#neuro_day:condition  2 0.0666  0.0333   45.49 4.27e-05 ***
#Residuals            8 0.0059  0.0007                     
#Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ‘ ’ 1 

## In ANOVA test, a significant p-value indicates that some of the group means are different, but we don't know which pairs of groups are different. It's possible to perform multiple pairwise-comparison, to determine if the mean difference between specific pairs of group are statistically significant.

turkey <- TukeyHSD(res.aov2)
oct4_stats <- data.frame(turkey$`neuro_day:condition`) %>%
  rownames_to_column(var = "comparison")

# filter only comparison that matters
comparison_list <- c("D1:ct-D0:ct",
                "D2:ct-D0:ct",
                "D3:ct-D0:ct",
                # dox
                "D1:dox-D1:ct",
                "D2:dox-D2:ct",
                "D3:dox-D3:ct",
                "D3:wd-D3:ct",
                # dif dox
                "D1:dox-D0:ct",
                "D2:dox-D0:ct",
                "D3:dox-D0:ct",
                "D3:wd-D0:ct")

oct4_stats <- oct4_stats %>%
  filter(comparison %in% comparison_list) %>%
  mutate(sig0.05 = ifelse(oct4_stats$p.adj <= 0.05 && oct4_stats$p.adj > 0.01, "*", "no"),
         sig0.01 = ifelse(oct4_stats$p.adj <= 0.01 && oct4_stats$p.adj > 0.001, "**", "no"),
         sig0.001 = ifelse(oct4_stats$p.adj <= 0.001, "***", "no"))
         
```

```{r}
# Example data
group5 <- SOX2 %>%
  ungroup () %>%
  filter(Time == "0h", Sample == "C5") %>%
  select(Relative.Normalized.Expression)
group6 <- SOX2 %>%
  ungroup () %>%
  filter(Time == "36h", Sample == "C5") %>%
  select(Relative.Normalized.Expression)

# Perform t-test
result <- t.test(group5, group6, var.equal = FALSE)

# Display the result
print(result)

```

